PLUGIN=mpeg4
DEFS= -DMPEG4 -DMSMPEG4
DEFFILE = mpeg4/mpeg4.def
SRCFILES_ARM  = mpeg4/stdafx.c
SRCFILES_ARM += mpeg4/divx3_data.c 
SRCFILES_ARM += mpeg4/divx3_header.c 
SRCFILES_ARM += mpeg4/divx3_mblock.c 
SRCFILES_ARM += mpeg4/divx3_vlc.c
SRCFILES_ARM += mpeg4/h263_header.c 
SRCFILES_ARM += mpeg4/h263_mblock.c 
SRCFILES_ARM += mpeg4/h263_vld.c
SRCFILES_ARM += mpeg4/mp4_vld_mpeg.c 
SRCFILES_ARM += mpeg4/mp4_decode.c 
SRCFILES_ARM += mpeg4/mp4_header.c 
SRCFILES_ARM += mpeg4/mp4_mblock.c
SRCFILES_ARM += mpeg4/mp4_mv.c 
SRCFILES_ARM += mpeg4/mp4_predict.c 
SRCFILES_ARM += mpeg4/mp4_stream.c 
SRCFILES_ARM += mpeg4/mp4_vld_h263.c

include plugin.inc
